<?php

/**
 * PluginModulesPolymorphismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginModulesPolymorphismTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginModulesPolymorphismTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginModulesPolymorphism');
    }
}