<?php

/**
 * PluginTopMenuPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTopMenuPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginTopMenuPermissionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTopMenuPermissions');
    }
}