<?php

/**
 * PluginLateralMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLateralMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginLateralMenuTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLateralMenu');
    }
}