<?php

/**
 * PluginTopMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTopMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginTopMenuTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTopMenu');
    }
}