<?php

/**
 * PluginLateralMenuPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLateralMenuPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginLateralMenuPermissionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLateralMenuPermissions');
    }
}